import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import SessionWrapper from '@/components/session-wrapper/SessionWrapper';
import theme from '../theme';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'NextJS Keycloak',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionWrapper>
			<html lang="en">
				<body className={inter.className}>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>{children} </ThemeProvider>
					</AppRouterCacheProvider>
				</body>
			</html>
		</SessionWrapper>
	);
}
